insert into public.brainstorm_areas(name,slug,display_order) values ('Marketing','marketing',1),('Adm: RH e Financeiro','adm-rh-financeiro',2),('Comercial','comercial',3),('Desenvolvimento','desenvolvimento',4),('Operacional','operacional',5);
insert into public.brainstorm_sessions(code,title,status,admin_pin_hash) values('ALPHA2026','Encontro de Crescimento 2026','WAITING',extensions.crypt('2468',extensions.gen_salt('bf')));
insert into public.brainstorm_rounds(session_id,area_id,title,question,supporting_text,display_order,duration_seconds)
select s.id,a.id,q.title,q.question,q.supporting_text,q.ord,300
from public.brainstorm_sessions s
cross join lateral(values
 ('marketing','Marketing — Crescimento','Como podemos ampliar o alcance da Alpha entre empresários e importadores com o perfil certo e transformar esse público em leads qualificados para o comercial?','Pilar: Crescimento',1),
 ('marketing','Marketing — Redução de custos','Como podemos reduzir o custo por lead do tráfego pago e identificar quais campanhas realmente geram vendas, para concentrar o investimento nas ações de maior retorno?','Pilar: Redução de custos',2),
 ('marketing','Marketing — Otimização','Como podemos estruturar o fluxo do marketing interno para que as aprovações e as demandas operacionais — como posts, apresentações, materiais internos e artes — não prejudiquem a captação de conteúdo e a análise de resultados?','Pilar: Otimização',3),
 ('marketing','Marketing — Pergunta aberta','Na sua percepção, qual dor, gargalo ou oportunidade relacionada ao marketing da Alpha ainda não foi mencionada e que, se trabalhada, poderia gerar um impacto relevante para a empresa?','Pilar: Pergunta aberta',4),
 ('comercial','Comercial — Conversão','Qual ação teria maior impacto para aumentar nossa taxa de conversão de vendas?','Pilar: Crescimento · Tema: Conversão',5),
 ('comercial','Comercial — Valor percebido e conversão','O que poderíamos fazer para que nossos clientes enxergassem mais valor na assessoria antes de receberem a proposta?','Pilar: Crescimento · Tema: Valor Percebido/Conversão',6),
 ('comercial','Comercial — Ciclo de venda','O que faria nossos clientes fecharem mais rápido?','Pilar: Otimização · Tema: Ciclo de Venda',7),
 ('comercial','Comercial — Produtividade','Qual mudança faria cada Closer fechar mais contratos na mesma jornada de trabalho?','Pilar: Redução de custos · Tema: Produtividade',8),
 ('comercial','Comercial — Inovação','Se você fosse Diretor Comercial da Alpha por um dia, qual seria a primeira decisão que tomaria para aumentar nossos resultados?','Pilar: Pergunta aberta · Tema: Inovação',9),
 ('operacional','Operacional — Capacidade e Deferimento','Como podemos reduzir o tempo de duração dos processos e aumentar a quantidade de deferimentos na primeira análise, ampliando a capacidade da Equipe Operacional para atender mais clientes com qualidade?','Pilar: Crescimento · Tema: Capacidade operacional e resultados',10),
 ('operacional','Operacional — Protocolos no Fim do Mês','Que mudanças podemos implementar no fluxo entre Comercial, cliente e Operacional para antecipar a coleta e a validação dos documentos, reduzindo o acúmulo de processos para protocolo nos últimos dias do mês?','Pilar: Redução de custos · Tema: Acúmulo de protocolos no fim do mês',11),
 ('operacional','Operacional — Gestão de Demandas e Agenda','Como podemos organizar e priorizar demandas, reuniões, atendimentos e prazos para melhorar a produtividade da Equipe Operacional?','Pilar: Otimização · Tema: Gestão de demandas e agenda',12),
 ('operacional','Operacional — Base de Conhecimento','Como podemos estruturar e manter atualizada uma base de conhecimento sobre os entendimentos de diferentes fiscais e regiões, facilitando sua consulta pela Operacional e pelo Comercial?','Pilar: Otimização · Tema: Base de conhecimento e alinhamento comercial',13),
 ('operacional','Operacional — Pergunta Aberta','Na sua percepção, qual dor, gargalo ou oportunidade da Equipe Operacional ainda não foi mencionada e que, se resolvida, poderia reduzir retrabalho, melhorar o atendimento ou aumentar a capacidade de entrega da Alpha?','Pilar: Pergunta aberta',14),
 ('adm-rh-financeiro','Administrativo — Controle de Ponto','Que ações ou mudanças de processo podemos implementar para reduzir a quantidade de ajustes de ponto e aumentar a autonomia dos colaboradores no registro correto da jornada?','Pilar: Redução de custos · Tema: Controle de Ponto (RH)',15),
 ('adm-rh-financeiro','Administrativo — Recrutamento e Seleção','O que podemos fazer para atrair candidatos mais qualificados, ampliar nossas fontes de recrutamento e reduzir o tempo de contratação sem comprometer a qualidade da seleção?','Pilar: Crescimento · Tema: Recrutamento e Seleção (RH)',16),
 ('adm-rh-financeiro','Administrativo — Previsibilidade Financeira','O que podemos fazer, como empresa, para tornar nosso faturamento mais previsível e fornecer ao Financeiro informações que permitam um planejamento mais assertivo do fluxo de caixa?','Pilar: Crescimento · Tema: Previsibilidade Financeira',17),
 ('adm-rh-financeiro','Administrativo — Produtividade e Processos','Qual processo da empresa hoje gera mais retrabalho, demora ou desperdício de tempo e como poderíamos simplificá-lo para aumentar nossa produtividade?','Pilar: Otimização · Tema: Produtividade e Processos',18),
 ('adm-rh-financeiro','Administrativo — Formalização de Contratos','Quais mudanças podemos implementar no fluxo de aprovação e formalização das propostas comerciais para garantir que os contratos sejam elaborados apenas quando as condições estiverem definitivamente validadas, reduzindo retrabalho e aumentando a eficiência do processo?','Pilar: Redução de custos · Tema: Assertividade na Formalização de Contratos (Financeiro)',19),
 ('desenvolvimento','Desenvolvimento/TI — Tecnologia para Crescimento','Que solução digital, automação ou recurso tecnológico poderíamos criar para aumentar o valor entregue aos clientes, gerar novas fontes de receita ou tornar os serviços da Alpha mais escaláveis?','Pilar: Crescimento · Tema: Tecnologia aplicada à geração de valor',20),
 ('desenvolvimento','Desenvolvimento/TI — Automação de Atividades','Qual atividade manual, repetitiva ou sujeita a erros deveria ser priorizada para automação e quanto tempo ou custo poderíamos economizar com essa mudança?','Pilar: Redução de custos · Tema: Automação de atividades manuais',21),
 ('desenvolvimento','Desenvolvimento/TI — Priorização e Entrega','Como podemos melhorar o processo de solicitação, priorização, desenvolvimento e acompanhamento das demandas de tecnologia para entregar soluções mais rapidamente e com maior alinhamento às necessidades das áreas?','Pilar: Otimização · Tema: Priorização e entrega de demandas',22),
 ('desenvolvimento','Desenvolvimento/TI — Pergunta Aberta','Na sua percepção, qual problema, oportunidade ou risco tecnológico da Alpha ainda não foi mencionado e que, se trabalhado, poderia aumentar a eficiência, a segurança ou a capacidade de crescimento da empresa?','Pilar: Pergunta aberta',23)
) q(slug,title,question,supporting_text,ord)
join public.brainstorm_areas a on a.slug=q.slug where s.code='ALPHA2026';

update public.brainstorm_rounds set
 pillar=case when supporting_text like 'Pilar: Crescimento%' then 'Crescimento' when supporting_text like 'Pilar: Redução de custos%' then 'Redução de custos' when supporting_text like 'Pilar: Otimização%' then 'Otimização' when supporting_text like 'Pilar: Pergunta aberta%' then 'Pergunta aberta' end,
 topic=case when supporting_text like '%Tema: %' then split_part(supporting_text,'Tema: ',2) else null end
where supporting_text like 'Pilar:%';

update public.brainstorm_rounds set context_text='Atualmente, temos 10 colaboradores que batem ponto e realizam, em média, cerca de 15 ajustes de ponto por mês. Embora utilizemos um sistema de ponto digital, ainda há recorrência de esquecimentos e inconsistências nos registros, gerando retrabalho para o RH.',kpis=array['Quantidade de ajustes de ponto por mês'] where title='Administrativo — Controle de Ponto';
update public.brainstorm_rounds set context_text='Nosso processo seletivo é composto por três etapas: entrevista com RH, entrevista com RH e líder e dia de vivência. Apesar das divulgações em plataformas de emprego e grupos de WhatsApp e Facebook, algumas vagas permanecem abertas entre um e cinco meses devido à dificuldade em atrair candidatos qualificados.',kpis=array['Tempo médio de fechamento das vagas','Quantidade de candidatos qualificados por vaga','Taxa de aprovação dos candidatos entrevistados','Tempo entre abertura e contratação'] where title='Administrativo — Recrutamento e Seleção';
update public.brainstorm_rounds set context_text='Atualmente enfrentamos oscilações significativas na previsibilidade financeira. A falta de previsibilidade compromete o planejamento e impacta diretamente o fluxo de caixa.',kpis=array['Fluxo de caixa previsto × realizado','Redução das variações entre o planejado e o realizado'] where title='Administrativo — Previsibilidade Financeira';
update public.brainstorm_rounds set kpis=array['Redução do tempo de execução dos processos','Redução de retrabalho','Ganho de produtividade por processo otimizado'] where title='Administrativo — Produtividade e Processos';
update public.brainstorm_rounds set context_text='Atualmente, em alguns processos, os contratos são elaborados antes da definição final das condições comerciais. Quando ocorrem renegociações ou alterações após o envio para elaboração, o Financeiro precisa refazer o documento diversas vezes, aumentando o retrabalho, consumindo tempo da equipe e atrasando a formalização dos serviços.',kpis=array['Tempo gasto com retrabalho na elaboração de contratos'] where title='Administrativo — Formalização de Contratos';
update public.brainstorm_rounds set context_text='A duração dos processos, as exigências adicionais e os indeferimentos que demandam nova análise limitam a capacidade da equipe e prolongam a entrega de resultados aos clientes.',kpis=array['Tempo médio de duração dos processos','Taxa de deferimento na primeira análise','Quantidade de processos concluídos por analista','Índice de retrabalho ou exigências adicionais'] where title='Operacional — Capacidade e Deferimento';
update public.brainstorm_rounds set context_text='Os processos possuem um mês de protocolo definido e dependem da coleta de documentos e informações atualizadas. Com frequência, pendências se concentram na última semana e especialmente no último dia útil, sobrecarregando a equipe.',kpis=array['Processos protocolados na última semana do mês','Processos protocolados no último dia útil','Tempo médio de coleta de documentos','Documentos pendentes próximos ao prazo','Horas extras ou esforço concentrado no fechamento'] where title='Operacional — Protocolos no Fim do Mês';
update public.brainstorm_rounds set context_text='A equipe concilia reuniões internas e com clientes, análise e protocolo de documentos, respostas em grupos e outras demandas com diferentes níveis de urgência, tornando difícil organizar prioridades e agendas.',kpis=array['Demandas concluídas dentro do prazo','Número de reuniões ou interrupções por analista','Demandas urgentes ou reprogramadas','Tempo dedicado a atividades prioritárias'] where title='Operacional — Gestão de Demandas e Agenda';
update public.brainstorm_rounds set context_text='Entendimentos de fiscais e particularidades regionais mudam ou ficam dispersos. A ausência de uma fonte atualizada dificulta a consulta pela Operacional e o alinhamento do Comercial antes de propor soluções aos clientes.',kpis=array['Tempo gasto procurando informações','Atualizações realizadas na base de conhecimento','Consultas resolvidas sem novo alinhamento interno','Propostas comerciais alinhadas ao entendimento operacional'] where title='Operacional — Base de Conhecimento';
update public.brainstorm_rounds set context_text='A tecnologia pode ampliar o valor percebido pelos clientes, permitir novas ofertas e aumentar a capacidade de atendimento sem exigir crescimento proporcional da estrutura.',kpis=array['Receita gerada por soluções digitais','Adoção da solução pelos clientes','Clientes atendidos sem aumento proporcional da equipe','Novos produtos ou serviços lançados'] where title='Desenvolvimento/TI — Tecnologia para Crescimento';
update public.brainstorm_rounds set context_text='Atividades repetitivas consomem tempo das equipes, aumentam custos e podem gerar erros. A priorização deve considerar impacto, frequência e viabilidade da automação.',kpis=array['Horas de trabalho manual eliminadas','Custo economizado','Redução de erros','Quantidade de tarefas automatizadas','Tempo necessário para recuperar o investimento'] where title='Desenvolvimento/TI — Automação de Atividades';
update public.brainstorm_rounds set context_text='Demandas de diferentes áreas competem por atenção e nem sempre chegam com prioridade, escopo ou resultado esperado claramente definidos, o que pode causar espera, retrabalho e desalinhamento.',kpis=array['Tempo entre solicitação e entrega','Demandas concluídas no prazo','Demandas reabertas ou refeitas','Satisfação das áreas solicitantes','Quantidade de demandas paradas ou sem prioridade definida'] where title='Desenvolvimento/TI — Priorização e Entrega';
