import {FormEvent,useEffect,useState} from 'react';import {useParams} from 'react-router-dom';import {Clock3} from 'lucide-react';import {Chrome} from '../components/Chrome';import {ContinuousIdeation} from '../components/ContinuousIdeation';import {ContinuousVoting} from '../components/ContinuousVoting';import {configured,supabase} from '../lib/supabase';import {demoAreas,demoRound} from '../lib/demo';import {clearParticipant,restoreParticipant,saveParticipant} from '../lib/storage';import {useSession} from '../hooks/useSession';import {Area,Idea,Participant,Round} from '../types';
import {ResultsDashboard} from '../components/ResultsDashboard';
function RoundDetails({round}:{round:Round}){return <><p className="font-semibold text-brand-700">{round.title}</p>{(round.pillar||round.topic)&&<p className="mt-2 text-sm font-semibold text-brand-700">{round.pillar&&`Pilar: ${round.pillar}`}{round.pillar&&round.topic?' · ':''}{round.topic&&`Tema: ${round.topic}`}</p>}<h1 className="mt-2 text-3xl font-black">{round.question}</h1>{round.context_text&&<div className="card mt-5 bg-slate-50"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Contexto</p><p className="mt-2 text-sm leading-relaxed text-slate-700">{round.context_text}</p></div>}{round.kpis&&round.kpis.length>0&&<div className="mt-4"><p className="text-sm font-bold">Indicadores relacionados</p><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-600">{round.kpis.map(kpi=><li key={kpi}>{kpi}</li>)}</ul></div>}{!round.pillar&&round.supporting_text&&<p className="mt-3 text-slate-600">{round.supporting_text}</p>}</>}
export default function SessionPage(){const code=(useParams().code||'').toUpperCase();const {session,loading,online,reload}=useSession(code);const [areas,setAreas]=useState<Area[]>([]);const [participant,setParticipant]=useState<Participant|null>(null);const [round,setRound]=useState<Round|null>(null);const [myIdeas,setMyIdeas]=useState<Idea[]>([]);const [text,setText]=useState(localStorage.getItem(`draft:${code}`)||'');const [expected,setExpected]=useState('');const [busy,setBusy]=useState(false);
useEffect(()=>{if(!configured){setAreas(demoAreas);return}supabase.from('brainstorm_areas').select('*').eq('active',true).order('display_order').then(({data})=>setAreas(data||[]))},[]);
useEffect(()=>{if(!session)return;const token=restoreParticipant(code);if(!token)return;if(!configured){const raw=localStorage.getItem(`brainstorm:${code}:demo-participant`);if(raw)setParticipant(JSON.parse(raw));return}supabase.rpc('brainstorm_restore_participant',{p_session_code:code,p_anonymous_token:token}).then(({data})=>setParticipant(data?.[0]||null))},[session?.id]);
useEffect(()=>{if(!session)return;if(!configured){setRound(demoRound);return}if(session.current_round_id)supabase.from('brainstorm_rounds').select('*').eq('id',session.current_round_id).single().then(({data})=>setRound(data));else setRound(null)},[session?.current_round_id]);
useEffect(()=>{if(!configured||!participant)return;const touch=()=>void supabase.rpc('brainstorm_participant_heartbeat',{p_session_id:participant.session_id,p_participant_id:participant.id,p_token:participant.anonymous_token});touch();const timer=setInterval(touch,30000);return()=>clearInterval(timer)},[participant?.id]);
useEffect(()=>{if(!configured)return;if(participant&&round)supabase.rpc('brainstorm_get_my_ideas',{p_session_id:participant.session_id,p_participant_id:participant.id,p_token:participant.anonymous_token,p_round_id:round.id}).then(({data})=>setMyIdeas(data||[]))},[participant?.id,round?.id]);
const join=async(areaId:string)=>{if(!session)return;setBusy(true);const token=crypto.randomUUID();if(!configured){const p={id:crypto.randomUUID(),session_id:session.id,anonymous_token:token,primary_area_id:areaId};saveParticipant(code,token);localStorage.setItem(`brainstorm:${code}:demo-participant`,JSON.stringify(p));setParticipant(p);setBusy(false);return}const {data,error}=await supabase.rpc('brainstorm_join_session',{p_session_code:code,p_anonymous_token:token,p_area_id:areaId});if(!error&&data?.[0]){saveParticipant(code,token);setParticipant(data[0])}setBusy(false)};
const submitIdea=async(e:FormEvent)=>{e.preventDefault();if(!session||!participant||!round||!text.trim())return;setBusy(true);if(!configured){setMyIdeas(v=>[...v,{id:crypto.randomUUID(),text:text.trim(),expected_result:expected.trim()||null,created_at:new Date().toISOString()}]);setText('');setExpected('');localStorage.removeItem(`draft:${code}`);setBusy(false);return}const {data,error}=await supabase.rpc('brainstorm_submit_idea',{p_session_id:session.id,p_round_id:round.id,p_participant_id:participant.id,p_token:participant.anonymous_token,p_text:text.trim(),p_expected_result:expected.trim()||null});if(!error){setMyIdeas(v=>[...v,data]);setText('');setExpected('');localStorage.removeItem(`draft:${code}`)}setBusy(false)};
if(loading)return <Chrome><p className="text-center">Carregando sessão…</p></Chrome>;if(!session)return <Chrome><div className="card mx-auto max-w-lg text-center"><h1 className="text-xl font-bold">Sessão não encontrada</h1><button onClick={reload} className="btn-primary mt-5">Tentar novamente</button></div></Chrome>;
if(!participant)return <Chrome online={online}><div className="mx-auto max-w-xl"><p className="text-sm font-semibold text-brand-700">{session.title}</p><h1 className="mt-2 text-3xl font-black">Em qual área você trabalha?</h1><p className="mt-2 text-slate-600">Escolha uma opção para entrar. Nenhum dado pessoal será solicitado.</p><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3">{areas.map(a=><button disabled={busy} onClick={()=>join(a.id)} className="card min-h-24 text-left font-bold hover:border-brand-500 hover:bg-brand-50" key={a.id}>{a.name}</button>)}</div></div></Chrome>;
const area=areas.find(a=>a.id===participant.primary_area_id);const waitingCopy:Record<string,[string,string]>={AI_GROUPING:['Ideias em agrupamento','As contribuições estão sendo organizadas para a votação.'],GROUP_REVIEW:['Ideias em revisão','O facilitador está preparando a sequência da votação.'],VOTING_WAITING:['Votação pausada','Seu voto foi preservado. Aguarde a próxima ideia.'],RESULTS:['Votação concluída','Os resultados estão sendo preparados.'],FINISHED:['Evento finalizado','Obrigado pela sua participação.']};const copy=waitingCopy[session.status]||['Aguardando o facilitador','Você está na sala certa. Esta tela avançará automaticamente.'];const waiting=<div className="card mx-auto max-w-xl text-center"><div className="mx-auto mb-5 grid size-16 place-items-center rounded-full bg-brand-50 text-brand-700"><Clock3/></div><p className="font-semibold text-brand-700">{area?.name}</p><h1 className="mt-2 text-2xl font-black">{copy[0]}</h1><p className="mt-3 text-slate-600">{copy[1]}</p>{session.status==='WAITING'&&<button className="mt-6 text-sm underline" onClick={()=>{clearParticipant(code);setParticipant(null)}}>Trocar de área</button>}</div>;
if((session.status==='WAITING'||session.status==='IDEATION_OPEN'))return <ContinuousIdeation session={session} participant={participant} online={online}/>;
if(session.status==='RESULTS'||session.status==='FINISHED')return <Chrome online={online}><ResultsDashboard code={code} published title="Resultados do Brainstorm"/></Chrome>;
if(session.status==='VOTING_OPEN')return <ContinuousVoting session={session} participant={participant} online={online}/>;
return <Chrome online={online}>{waiting}</Chrome>}
