import {ReactNode,useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,Pause,Play,RefreshCw,Square,Users,Vote} from 'lucide-react';
import {AdminWorkspace} from './AdminGrouping';

type CallResult={ok:boolean;data?:Record<string,unknown>;error?:string};
export type VotingProgress={participant_count:number;connected_count:number;current_idea_id:string|null;current_vote_count:number;approved_idea_count:number;idea_vote_counts:Record<string,number>};

export function AdminVotingControl({workspace,busy,onCall,onRefresh,onProgress}:{workspace:AdminWorkspace;busy:boolean;onCall:(action:string,payload?:Record<string,unknown>)=>Promise<CallResult>;onRefresh:()=>Promise<void>;onProgress:()=>Promise<VotingProgress|null>}){
 const [progress,setProgress]=useState<VotingProgress|null>(null);const approved=[...workspace.groups].filter(group=>group.approved).sort((a,b)=>a.display_order-b.display_order);const currentIndex=approved.findIndex(group=>group.id===workspace.session.current_consolidated_idea_id);const current=approved[currentIndex];const active=workspace.session.status==='VOTING_OPEN';const paused=workspace.session.status==='VOTING_WAITING';
 const refresh=async()=>setProgress(await onProgress());
 useEffect(()=>{void refresh();if(!active&&!paused)return;const timer=setInterval(()=>void refresh(),5000);return()=>clearInterval(timer)},[workspace.session.status,workspace.session.current_consolidated_idea_id]);
 const setStatus=async(status:string)=>{const result=await onCall('set_status',{status});if(result.ok){await onRefresh();await refresh()}};
 const pause=async()=>{if(confirm('Encerrar a votação desta ideia? Os participantes passarão para a tela de espera.'))await setStatus('VOTING_WAITING')};
 const reopen=async()=>{if(confirm(`Abrir a votação da ideia “${current?.title}”?`))await setStatus('VOTING_OPEN')};
 const navigate=async(delta:number)=>{const next=approved[currentIndex+delta];if(!next)return;const result=await onCall('select_current_idea',{group_id:next.id});if(result.ok){await onRefresh();await refresh()}};
 const finish=async()=>{if(confirm('Finalizar toda a votação e publicar os resultados? Esta ação encerra a avaliação dos participantes.'))await setStatus('RESULTS')};
 const total=progress?.participant_count||0;const votes=progress?.current_vote_count||0;const percentage=total?Math.round(votes/total*100):0;
 return <section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-semibold text-brand-700">Fase 4</p><h2 className="text-2xl font-black">Controle da votação ao vivo</h2><p className="mt-1 text-sm text-slate-600">Abra uma ideia por vez e acompanhe os votos recebidos.</p></div><button className="btn-secondary" onClick={refresh}><RefreshCw className="mr-2" size={17}/>Atualizar métricas</button></div>
  <div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric icon={<Users/>} label="Participantes registrados" value={total}/><Metric icon={<span className="size-3 rounded-full bg-green-500"/>} label="Conectados nos últimos 2 min" value={progress?.connected_count||0}/><Metric icon={<Vote/>} label="Votos na ideia atual" value={`${votes} (${percentage}%)`}/></div>
  <div className={`card mt-5 border-2 ${active?'border-green-500':'border-slate-200'}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><span className={`rounded-full px-3 py-1 text-xs font-bold ${active?'bg-green-100 text-green-800':paused?'bg-amber-100 text-amber-800':'bg-slate-100 text-slate-600'}`}>{active?'Votação aberta':paused?'Votação pausada':'Aguardando preparação'}</span><p className="mt-3 text-sm font-semibold text-brand-700">Ideia {currentIndex>=0?currentIndex+1:0} de {approved.length}</p><h3 className="mt-1 text-2xl font-black">{current?.title||'Nenhuma ideia selecionada'}</h3>{current?.description&&<p className="mt-2 text-slate-600">{current.description}</p>}</div>{active?<button className="btn-secondary text-amber-800" disabled={busy} onClick={pause}><Pause className="mr-2" size={18}/>Encerrar esta ideia</button>:paused&&current?<button className="btn-primary" disabled={busy} onClick={reopen}><Play className="mr-2" size={18}/>Abrir esta ideia</button>:null}</div>
   <div className="mt-5 h-3 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-brand-600 transition-all" style={{width:`${Math.min(100,percentage)}%`}}/></div><p className="mt-2 text-right text-xs text-slate-500">{votes} de {total} participantes registrados</p>
   <div className="mt-5 grid gap-3 sm:grid-cols-2"><button className="btn-secondary" disabled={busy||active||currentIndex<=0} onClick={()=>navigate(-1)}><ArrowLeft className="mr-2" size={18}/>Ideia anterior</button><button className="btn-primary" disabled={busy||active||currentIndex<0||currentIndex>=approved.length-1} onClick={()=>navigate(1)}>Próxima ideia<ArrowRight className="ml-2" size={18}/></button></div>
  </div>
  <div className="card mt-5"><h3 className="font-bold">Progresso por ideia</h3><div className="mt-3 space-y-2">{approved.map((group,index)=>{const count=progress?.idea_vote_counts?.[group.id]||0;const selected=group.id===workspace.session.current_consolidated_idea_id;return <div className={`flex items-center justify-between rounded-xl border p-3 ${selected?'border-brand-400 bg-brand-50':'border-slate-200'}`} key={group.id}><div className="flex items-center gap-3"><span className="grid size-7 place-items-center rounded-full bg-slate-900 text-xs font-bold text-white">{index+1}</span><span className="font-medium">{group.title}</span></div><span className="text-sm font-bold">{count} voto(s)</span></div>})}</div></div>
  {paused&&<button className="btn-secondary mt-5 w-full border-red-200 text-red-700" disabled={busy} onClick={finish}><Square className="mr-2" size={18}/>Finalizar votação e publicar resultados</button>}
 </section>
}

function Metric({icon,label,value}:{icon:ReactNode;label:string;value:number|string}){return <div className="card flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-brand-50 text-brand-700">{icon}</span><div><p className="text-sm text-slate-500">{label}</p><p className="text-xl font-black">{value}</p></div></div>}
