import {CheckCircle2,CircleAlert,PlayCircle,Radio} from 'lucide-react';
import {AdminWorkspace} from './AdminGrouping';

type CallResult={ok:boolean;data?:Record<string,unknown>;error?:string};

export function AdminVotingPreparation({workspace,busy,onCall,onRefresh}:{workspace:AdminWorkspace;busy:boolean;onCall:(action:string,payload?:Record<string,unknown>)=>Promise<CallResult>;onRefresh:()=>Promise<void>}){
 const groups=[...workspace.groups].sort((a,b)=>a.display_order-b.display_order);const approved=groups.filter(group=>group.approved);const linked=new Set(workspace.sources.map(source=>source.idea_id));const ungrouped=workspace.ideas.filter(idea=>!linked.has(idea.id)).length;const emptyApproved=approved.filter(group=>!workspace.sources.some(source=>source.consolidated_idea_id===group.id)).length;const selected=approved.find(group=>group.id===workspace.session.current_consolidated_idea_id);const inReview=workspace.session.status==='GROUP_REVIEW';const ready=approved.length>0&&emptyApproved===0&&ungrouped===0&&Boolean(selected)&&inReview;
 const select=async(groupId:string)=>{const result=await onCall('select_current_idea',{group_id:groupId});if(result.ok)await onRefresh()};
 const openVoting=async()=>{if(!ready||!confirm(`Abrir a votação com “${selected?.title}” como primeira ideia? Os participantes verão a tela de avaliação.`))return;const result=await onCall('set_status',{status:'VOTING_OPEN'});if(result.ok)await onRefresh()};
 return <section className="mt-8"><div><p className="font-semibold text-brand-700">Fase 3</p><h2 className="text-2xl font-black">Preparação da votação</h2><p className="mt-1 text-sm text-slate-600">Revise a sequência e escolha a primeira ideia antes de abrir a avaliação.</p></div>
  <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><CheckItem ok={approved.length>0&&emptyApproved===0} label="Ideias aprovadas" detail={emptyApproved?`${emptyApproved} sem contribuições`:`${approved.length} pronta(s)`}/><CheckItem ok={ungrouped===0} label="Contribuições tratadas" detail={ungrouped===0?'Nenhuma pendência':`${ungrouped} não agrupada(s)`}/><CheckItem ok={Boolean(selected)} label="Primeira ideia" detail={selected?.title||'Não selecionada'}/><CheckItem ok={inReview} label="Etapa de revisão" detail={inReview?'Revisão ativa':'Clique em Ir para revisão'}/></div>
  <div className="card mt-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold">Sequência aprovada</h3><p className="mt-1 text-sm text-slate-600">A ordem pode ser alterada pelos controles dos grupos acima.</p></div><span className="rounded-full bg-brand-50 px-3 py-1 text-sm font-bold text-brand-700">{approved.length} ideia(s)</span></div>
   <div className="mt-4 space-y-3">{approved.map((group,index)=>{const count=workspace.sources.filter(source=>source.consolidated_idea_id===group.id).length;const isSelected=group.id===workspace.session.current_consolidated_idea_id;return <div className={`rounded-xl border p-4 ${isSelected?'border-brand-500 bg-brand-50':'border-slate-200'}`} key={group.id}><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-slate-900 text-sm font-bold text-white">{index+1}</span><div><div className="flex items-center gap-2"><h4 className="font-bold">{group.title}</h4>{isSelected&&<span className="rounded-full bg-brand-600 px-2 py-0.5 text-xs font-bold text-white">Primeira</span>}</div><p className="mt-1 text-sm text-slate-600">{group.description||'Sem descrição'} · {count} contribuição(ões)</p></div></div><button className={isSelected?'btn-secondary':'btn-primary'} disabled={busy||!inReview||isSelected} onClick={()=>select(group.id)}><Radio className="mr-2" size={17}/>{isSelected?'Selecionada':'Começar por esta'}</button></div></div>})}{approved.length===0&&<div className="rounded-xl bg-slate-50 p-5 text-center text-sm text-slate-500">Aprove pelo menos um grupo na etapa anterior.</div>}</div>
  </div>
  <div className={`mt-5 rounded-2xl border p-5 ${ready?'border-green-200 bg-green-50':'border-amber-200 bg-amber-50'}`}><div className="flex gap-3">{ready?<CheckCircle2 className="shrink-0 text-green-700"/>:<CircleAlert className="shrink-0 text-amber-700"/>}<div><h3 className="font-bold">{ready?'Tudo pronto para votar':'Existem pendências antes da votação'}</h3><p className="mt-1 text-sm text-slate-700">{ready?`A votação começará pela ideia “${selected?.title}”.`:'Resolva os itens indicados acima. O servidor também bloqueará uma abertura incompleta.'}</p></div></div><button className="btn-primary mt-4 w-full" disabled={busy||!ready} onClick={openVoting}><PlayCircle className="mr-2" size={19}/>Confirmar e abrir votação</button></div>
 </section>
}

function CheckItem({ok,label,detail}:{ok:boolean;label:string;detail:string}){return <div className={`card border-l-4 ${ok?'border-l-green-500':'border-l-amber-500'}`}><div className="flex gap-2">{ok?<CheckCircle2 className="shrink-0 text-green-600" size={19}/>:<CircleAlert className="shrink-0 text-amber-600" size={19}/>}<div><p className="font-bold">{label}</p><p className="mt-1 text-sm text-slate-600">{detail}</p></div></div></div>}
