import {FormEvent,useMemo,useState} from 'react';
import {Check,ChevronDown,ChevronUp,FolderPlus,Pencil,RefreshCw,Search,Trash2,X} from 'lucide-react';

type Area={id:string;name:string;slug:string;display_order:number};
type Round={id:string;area_id:string;title:string;question:string;pillar:string|null;topic:string|null;display_order:number};
type Contribution={id:string;round_id:string;area_id:string;participant_id:string;text:string;expected_result:string|null;created_at:string};
type Group={id:string;session_id:string;area_id:string;title:string;description:string;approved:boolean;display_order:number;grouping_method:string};
type Source={consolidated_idea_id:string;idea_id:string};
export type AdminWorkspace={session:{id:string;status:string};areas:Area[];rounds:Round[];ideas:Contribution[];groups:Group[];sources:Source[];participants:{id:string;primary_area_id:string;last_seen_at:string}[]};
type CallResult={ok:boolean;data?:Record<string,unknown>;error?:string};

export function AdminGrouping({workspace,busy,onCall,onRefresh}:{workspace:AdminWorkspace;busy:boolean;onCall:(action:string,payload?:Record<string,unknown>)=>Promise<CallResult>;onRefresh:()=>Promise<void>}){
 const editable=['AI_GROUPING','GROUP_REVIEW'].includes(workspace.session.status);
 const [areaId,setAreaId]=useState('');const [roundId,setRoundId]=useState('');const [query,setQuery]=useState('');const [onlyUngrouped,setOnlyUngrouped]=useState(true);
 const [selected,setSelected]=useState<string[]>([]);const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [editing,setEditing]=useState<string|null>(null);const [message,setMessage]=useState('');
 const sourceByIdea=useMemo(()=>new Map(workspace.sources.map(source=>[source.idea_id,source.consolidated_idea_id])),[workspace.sources]);
 const roundsById=useMemo(()=>new Map(workspace.rounds.map(round=>[round.id,round])),[workspace.rounds]);
 const areasById=useMemo(()=>new Map(workspace.areas.map(area=>[area.id,area])),[workspace.areas]);
 const filtered=workspace.ideas.filter(idea=>(!areaId||idea.area_id===areaId)&&(!roundId||idea.round_id===roundId)&&(!onlyUngrouped||!sourceByIdea.has(idea.id))&&(!query||`${idea.text} ${idea.expected_result||''} ${roundsById.get(idea.round_id)?.question||''}`.toLowerCase().includes(query.toLowerCase())));
 const selectedAreas=new Set(selected.map(id=>workspace.ideas.find(idea=>idea.id===id)?.area_id).filter(Boolean));
 const ungrouped=workspace.ideas.filter(idea=>!sourceByIdea.has(idea.id)).length;
 const approved=workspace.groups.filter(group=>group.approved).length;
 const toggle=(id:string)=>setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);
 const create=async(event:FormEvent)=>{event.preventDefault();setMessage('');if(selectedAreas.size!==1){setMessage('Selecione contribuições de um único setor.');return}const result=await onCall('create_group',{area_id:[...selectedAreas][0],title,description,idea_ids:selected});if(!result.ok){setMessage(result.error||'Não foi possível criar o grupo.');return}setSelected([]);setTitle('');setDescription('');setMessage('Grupo criado.');await onRefresh()};
 const removeGroup=async(group:Group)=>{if(!confirm(`Excluir o grupo “${group.title}”? As contribuições voltarão para a lista de não agrupadas.`))return;const result=await onCall('delete_group',{group_id:group.id});setMessage(result.ok?'Grupo excluído.':result.error||'Não foi possível excluir.');if(result.ok){setEditing(null);await onRefresh()}};
 const move=async(group:Group,direction:-1|1)=>{const ordered=[...workspace.groups].sort((a,b)=>a.display_order-b.display_order);const index=ordered.findIndex(item=>item.id===group.id);const target=index+direction;if(target<0||target>=ordered.length)return;[ordered[index],ordered[target]]=[ordered[target],ordered[index]];const result=await onCall('reorder_groups',{group_ids:ordered.map(item=>item.id)});if(!result.ok)setMessage(result.error||'Não foi possível alterar a ordem.');else await onRefresh()};
 return <section className="mt-8">
  <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-semibold text-brand-700">Fase 2</p><h2 className="text-2xl font-black">Agrupamento manual</h2><p className="mt-1 text-sm text-slate-600">Organize contribuições semelhantes antes da votação.</p></div><button className="btn-secondary" disabled={busy} onClick={onRefresh}><RefreshCw className="mr-2" size={17}/>Atualizar</button></div>
  {!editable&&<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Para editar os grupos, clique em <strong>Iniciar agrupamento</strong> no fluxo da sessão.</div>}
  <div className="mt-5 grid gap-3 sm:grid-cols-4"><Metric label="Contribuições" value={workspace.ideas.length}/><Metric label="Não agrupadas" value={ungrouped}/><Metric label="Grupos" value={workspace.groups.length}/><Metric label="Aprovados" value={approved}/></div>
  <div className="mt-6 grid gap-6 lg:grid-cols-[1.1fr_.9fr]">
   <div>
    <div className="card"><div className="grid gap-3 sm:grid-cols-2"><label><span className="label">Setor</span><select className="field" value={areaId} onChange={e=>{setAreaId(e.target.value);setRoundId('')}}><option value="">Todos</option>{workspace.areas.map(area=><option value={area.id} key={area.id}>{area.name}</option>)}</select></label><label><span className="label">Pergunta</span><select className="field" value={roundId} onChange={e=>setRoundId(e.target.value)}><option value="">Todas</option>{workspace.rounds.filter(round=>!areaId||round.area_id===areaId).map(round=><option value={round.id} key={round.id}>{round.title}</option>)}</select></label></div><label className="mt-3 block"><span className="label">Pesquisar</span><span className="relative block"><Search className="absolute left-3 top-3.5 text-slate-400" size={18}/><input className="field pl-10" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar no texto da contribuição"/></span></label><label className="mt-4 flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={onlyUngrouped} onChange={e=>setOnlyUngrouped(e.target.checked)}/>Mostrar somente não agrupadas</label></div>
    <div className="mt-4 flex items-center justify-between"><h3 className="font-bold">Contribuições ({filtered.length})</h3>{selected.length>0&&<button className="text-sm font-semibold text-brand-700" onClick={()=>setSelected([])}>Limpar seleção</button>}</div>
    <div className="mt-3 max-h-[42rem] space-y-3 overflow-y-auto pr-1">{filtered.map(idea=>{const groupId=sourceByIdea.get(idea.id);const group=workspace.groups.find(item=>item.id===groupId);const round=roundsById.get(idea.round_id);return <label className={`card block cursor-pointer ${selected.includes(idea.id)?'border-brand-500 bg-brand-50':''}`} key={idea.id}><div className="flex gap-3"><input className="mt-1" type="checkbox" disabled={!editable||Boolean(groupId)} checked={selected.includes(idea.id)} onChange={()=>toggle(idea.id)}/><div><div className="flex flex-wrap gap-2 text-xs font-semibold"><span className="rounded-full bg-slate-100 px-2 py-1">{areasById.get(idea.area_id)?.name}</span>{round?.pillar&&<span className="rounded-full bg-brand-50 px-2 py-1 text-brand-700">{round.pillar}</span>}{group&&<span className="rounded-full bg-amber-50 px-2 py-1 text-amber-800">Em: {group.title}</span>}</div><p className="mt-2 font-medium">{idea.text}</p>{idea.expected_result&&<p className="mt-1 text-sm text-slate-600">Como ajuda: {idea.expected_result}</p>}<p className="mt-2 text-xs text-slate-500">{round?.title}</p></div></div></label>})}{filtered.length===0&&<div className="card text-center text-sm text-slate-500">Nenhuma contribuição encontrada.</div>}</div>
   </div>
   <div>
    <form className="card" onSubmit={create}><div className="flex items-center gap-2"><FolderPlus className="text-brand-700"/><h3 className="font-bold">Criar grupo</h3></div><p className="mt-2 text-sm text-slate-600">{selected.length} contribuição(ões) selecionada(s).</p><label className="mt-4 block"><span className="label">Título</span><input className="field" minLength={2} maxLength={160} required value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="mt-3 block"><span className="label">Descrição</span><textarea className="field min-h-24" maxLength={800} value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="btn-primary mt-4 w-full" disabled={!editable||busy||selected.length===0||selectedAreas.size!==1}>Criar grupo</button></form>
    {message&&<p role="status" className="mt-3 rounded-xl bg-slate-100 p-3 text-sm font-medium">{message}</p>}
    <div className="mt-5 flex items-center justify-between"><h3 className="font-bold">Grupos ({workspace.groups.length})</h3><span className="text-xs text-slate-500">ordem de votação</span></div>
    <div className="mt-3 space-y-3">{[...workspace.groups].sort((a,b)=>a.display_order-b.display_order).map((group,index)=>{const sourceIds=workspace.sources.filter(source=>source.consolidated_idea_id===group.id).map(source=>source.idea_id);return <div className="card" key={group.id}><div className="flex items-start justify-between gap-3"><div><span className={`rounded-full px-2 py-1 text-xs font-bold ${group.approved?'bg-green-100 text-green-800':'bg-slate-100 text-slate-600'}`}>{group.approved?'Aprovado':'Pendente'}</span><h4 className="mt-2 font-bold">{group.title}</h4><p className="mt-1 text-sm text-slate-600">{areasById.get(group.area_id)?.name} · {sourceIds.length} contribuição(ões)</p></div><div className="flex"><button aria-label="Subir grupo" disabled={!editable||index===0} className="p-2 disabled:opacity-30" onClick={()=>move(group,-1)}><ChevronUp size={18}/></button><button aria-label="Descer grupo" disabled={!editable||index===workspace.groups.length-1} className="p-2 disabled:opacity-30" onClick={()=>move(group,1)}><ChevronDown size={18}/></button><button aria-label="Editar grupo" disabled={!editable} className="p-2" onClick={()=>setEditing(editing===group.id?null:group.id)}>{editing===group.id?<X size={18}/>:<Pencil size={18}/>}</button><button aria-label="Excluir grupo" disabled={!editable} className="p-2 text-red-700" onClick={()=>removeGroup(group)}><Trash2 size={18}/></button></div></div>{editing===group.id&&<GroupEditor group={group} ideas={workspace.ideas.filter(idea=>idea.area_id===group.area_id)} sourceIds={sourceIds} sourceByIdea={sourceByIdea} busy={busy} onCall={onCall} onSaved={async text=>{setMessage(text);setEditing(null);await onRefresh()}}/>}</div>})}{workspace.groups.length===0&&<div className="card text-center text-sm text-slate-500">Os grupos criados aparecerão aqui.</div>}</div>
   </div>
  </div>
 </section>
}

function GroupEditor({group,ideas,sourceIds,sourceByIdea,busy,onCall,onSaved}:{group:Group;ideas:Contribution[];sourceIds:string[];sourceByIdea:Map<string,string>;busy:boolean;onCall:(action:string,payload?:Record<string,unknown>)=>Promise<CallResult>;onSaved:(message:string)=>Promise<void>}){
 const [title,setTitle]=useState(group.title);const [description,setDescription]=useState(group.description);const [approved,setApproved]=useState(group.approved);const [chosen,setChosen]=useState(sourceIds);const [error,setError]=useState('');
 const save=async()=>{setError('');const metadata=await onCall('update_group',{group_id:group.id,title,description,approved});if(!metadata.ok){setError(metadata.error||'Não foi possível atualizar.');return}const sources=await onCall('set_group_sources',{group_id:group.id,idea_ids:chosen});if(!sources.ok){setError(sources.error||'Os dados foram salvos, mas não foi possível atualizar as contribuições.');return}await onSaved('Grupo atualizado.')};
 return <div className="mt-4 border-t pt-4"><label><span className="label">Título</span><input className="field" value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="mt-3 block"><span className="label">Descrição</span><textarea className="field" value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="mt-3 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/><Check size={16}/>Aprovado para votação</label><p className="mt-4 text-sm font-bold">Contribuições do grupo</p><div className="mt-2 max-h-56 space-y-2 overflow-y-auto rounded-xl border p-3">{ideas.map(idea=>{const other=sourceByIdea.get(idea.id);return <label className={`flex gap-2 text-sm ${other&&other!==group.id?'opacity-40':''}`} key={idea.id}><input type="checkbox" disabled={Boolean(other&&other!==group.id)} checked={chosen.includes(idea.id)} onChange={()=>setChosen(current=>current.includes(idea.id)?current.filter(id=>id!==idea.id):[...current,idea.id])}/><span>{idea.text}{other&&other!==group.id?' (em outro grupo)':''}</span></label>})}</div><p className="mt-2 text-xs text-slate-500">Ao desmarcar, a contribuição volta para “não agrupadas” e pode formar um novo grupo.</p>{error&&<p className="mt-3 text-sm font-medium text-red-700">{error}</p>}<button className="btn-primary mt-4 w-full" disabled={busy||title.trim().length<2} onClick={save}>Salvar alterações</button></div>
}

function Metric({label,value}:{label:string;value:number}){return <div className="card"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>}
