import {FormEvent,useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,Send} from 'lucide-react';
import {Chrome} from './Chrome';
import {configured,supabase} from '../lib/supabase';
import {demoRound} from '../lib/demo';
import {Idea,Participant,Round,Session} from '../types';

function Details({round}:{round:Round}){return <><p className="font-semibold text-brand-700">{round.title}</p>{(round.pillar||round.topic)&&<p className="mt-2 text-sm font-semibold text-brand-700">{round.pillar&&`Pilar: ${round.pillar}`}{round.pillar&&round.topic?' · ':''}{round.topic&&`Tema: ${round.topic}`}</p>}<h1 className="mt-2 text-3xl font-black">{round.question}</h1>{round.context_text&&<div className="card mt-5 bg-slate-50"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Contexto</p><p className="mt-2 text-sm leading-relaxed text-slate-700">{round.context_text}</p></div>}{round.kpis&&round.kpis.length>0&&<div className="mt-4"><p className="text-sm font-bold">Indicadores relacionados</p><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-600">{round.kpis.map(kpi=><li key={kpi}>{kpi}</li>)}</ul></div>}</>}

export function ContinuousIdeation({session,participant,online}:{session:Session;participant:Participant;online:boolean}){
 const progressKey=`brainstorm:${session.code}:${participant.id}:question`;
 const completeKey=`brainstorm:${session.code}:${participant.id}:ideation-complete`;
 const pendingKey=`brainstorm:${session.code}:${participant.id}:pending-ideas`;
 const [rounds,setRounds]=useState<Round[]>([]);const [index,setIndex]=useState(()=>Number(localStorage.getItem(progressKey)||0));const [ideas,setIdeas]=useState<Idea[]>([]);const [text,setText]=useState('');const [expected,setExpected]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [complete,setComplete]=useState(localStorage.getItem(completeKey)==='true');
 const round=rounds[index];
 useEffect(()=>{if(!configured){setRounds([demoRound]);setIndex(0);setLoading(false);return}supabase.from('brainstorm_rounds').select('*').eq('session_id',session.id).order('display_order').then(({data,error})=>{if(error){setError('Não foi possível carregar as perguntas.');setLoading(false);return}const list=data||[];setRounds(list);setIndex(current=>Math.min(current,Math.max(0,list.length-1)));setLoading(false)})},[session.id]);
 useEffect(()=>{if(!round)return;setIdeas([]);setText(localStorage.getItem(`draft:${session.code}:${round.id}`)||'');setExpected('');if(configured)supabase.rpc('brainstorm_get_my_ideas',{p_session_id:session.id,p_participant_id:participant.id,p_token:participant.anonymous_token,p_round_id:round.id}).then(({data,error})=>{if(error)setError('Não foi possível carregar suas ideias.');else setIdeas(data||[])})},[round?.id]);
 useEffect(()=>{if(!configured||!online)return;let cancelled=false;const resend=async()=>{const pending:PendingIdea[]=JSON.parse(localStorage.getItem(pendingKey)||'[]');if(!pending.length)return;const remaining:PendingIdea[]=[];for(const item of pending){const {data,error}=await supabase.rpc('brainstorm_submit_idea',{p_session_id:session.id,p_round_id:item.round_id,p_participant_id:participant.id,p_token:participant.anonymous_token,p_text:item.text,p_expected_result:item.expected_result,p_client_submission_id:item.submission_id});if(error)remaining.push(item);else if(!cancelled&&item.round_id===round?.id)setIdeas(current=>current.some(idea=>idea.id===data.id)?current:[...current,data])}localStorage.setItem(pendingKey,JSON.stringify(remaining));if(!cancelled&&pending.length>remaining.length)setError(remaining.length?'Algumas ideias pendentes foram enviadas. As demais serão reenviadas automaticamente.':'Suas ideias pendentes foram enviadas com sucesso.')};void resend();return()=>{cancelled=true}},[online,participant.id,round?.id]);
 const move=(next:number)=>{const safe=Math.max(0,Math.min(rounds.length-1,next));setIndex(safe);setComplete(false);localStorage.setItem(progressKey,String(safe));localStorage.removeItem(completeKey);setError('');window.scrollTo({top:0,behavior:'smooth'})};
 const submit=async(event:FormEvent)=>{event.preventDefault();if(!round||!text.trim()||busy)return;setBusy(true);setError('');if(!configured){setIdeas(v=>[...v,{id:crypto.randomUUID(),text:text.trim(),expected_result:expected.trim()||null,created_at:new Date().toISOString()}]);setText('');setExpected('');setBusy(false);return}const pending:PendingIdea[]=JSON.parse(localStorage.getItem(pendingKey)||'[]');const cleanText=text.trim();const cleanExpected=expected.trim()||null;const existing=pending.find(item=>item.round_id===round.id&&item.text===cleanText&&item.expected_result===cleanExpected);const item:PendingIdea=existing||{submission_id:crypto.randomUUID(),round_id:round.id,text:cleanText,expected_result:cleanExpected};if(!existing)localStorage.setItem(pendingKey,JSON.stringify([...pending,item]));const {data,error}=await supabase.rpc('brainstorm_submit_idea',{p_session_id:session.id,p_round_id:round.id,p_participant_id:participant.id,p_token:participant.anonymous_token,p_text:item.text,p_expected_result:item.expected_result,p_client_submission_id:item.submission_id});if(error)setError('Sua ideia ficou salva neste dispositivo e será reenviada automaticamente quando a conexão voltar.');else{localStorage.setItem(pendingKey,JSON.stringify(pending.filter(entry=>entry.submission_id!==item.submission_id)));setIdeas(v=>v.some(idea=>idea.id===data.id)?v:[...v,data]);setText('');setExpected('');localStorage.removeItem(`draft:${session.code}:${round.id}`)}setBusy(false)};
 const finish=()=>{localStorage.setItem(completeKey,'true');setComplete(true);window.scrollTo({top:0,behavior:'smooth'})};
 if(loading)return <Chrome online={online}><p className="text-center">Carregando perguntas…</p></Chrome>;
 if(complete)return <Chrome online={online}><div className="card mx-auto max-w-xl text-center"><Check className="mx-auto text-brand-600" size={48}/><h1 className="mt-4 text-2xl font-black">Contribuições concluídas</h1><p className="mt-2 text-slate-600">Suas ideias foram registradas. Você ainda pode revisar as perguntas enquanto a coleta estiver aberta.</p><button className="btn-secondary mt-6" onClick={()=>move(0)}>Revisar perguntas</button></div></Chrome>;
 if(!round)return <Chrome online={online}><div className="card text-center">Nenhuma pergunta disponível.</div></Chrome>;
 return <Chrome online={online}><div className="mb-6"><div className="flex items-center justify-between text-sm font-semibold"><span>Pergunta {index+1} de {rounds.length}</span><span>{Math.round((index+1)/rounds.length*100)}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-brand-600 transition-all" style={{width:`${(index+1)/rounds.length*100}%`}}/></div></div><div className="grid gap-6 md:grid-cols-[1fr_.75fr]"><section><Details round={round}/><form className="card mt-6 space-y-4" onSubmit={submit}><label><span className="label">Qual é a sua ideia? *</span><textarea maxLength={500} required className="field min-h-28" value={text} onChange={e=>{setText(e.target.value);localStorage.setItem(`draft:${session.code}:${round.id}`,e.target.value)}}/></label><label><span className="label">Como isso ajudaria a empresa? (opcional)</span><textarea maxLength={500} className="field" value={expected} onChange={e=>setExpected(e.target.value)}/></label>{error&&<p role="alert" className="text-sm font-medium text-red-700">{error}</p>}<button disabled={busy} className="btn-primary w-full"><Send size={18} className="mr-2"/>{busy?'Salvando…':'Enviar ideia'}</button><p className="text-center text-xs text-slate-500">Você pode enviar quantas ideias quiser nesta pergunta.</p></form><div className="mt-5 flex gap-3"><button disabled={index===0} className="btn-secondary flex-1" onClick={()=>move(index-1)}><ArrowLeft size={18} className="mr-2"/>Anterior</button>{index<rounds.length-1?<button className="btn-primary flex-1" onClick={()=>move(index+1)}>Próxima<ArrowRight size={18} className="ml-2"/></button>:<button className="btn-primary flex-1" onClick={finish}>Concluir</button>}</div></section><aside><h2 className="mb-3 font-bold">Suas ideias nesta pergunta ({ideas.length})</h2><div className="space-y-3">{ideas.map(idea=><div className="card flex gap-3" key={idea.id}><Check className="mt-1 shrink-0 text-brand-600" size={18}/><p>{idea.text}</p></div>)}</div></aside></div></Chrome>;
}

type PendingIdea={submission_id:string;round_id:string;text:string;expected_result:string|null};
