import {ReactNode,useEffect,useMemo,useState} from 'react';
import {BarChart3,RefreshCw,Sparkles,Trophy,Vote} from 'lucide-react';
import {configured,supabase} from '../lib/supabase';

type ResultRow={id:string;area_id:string;area_name:string;title:string;description:string;display_order:number;vote_count:number;contribution_count:number;revenue:number|null;margin:number|null;savings:number|null;ease:number|null;speed:number|null;scalability:number|null;automation:number|null;risk:number|null;customer:number|null;strategy:number|null;impact:number|null;viability:number|null;overall_score:number|null;classification:string};
type NumericKey='overall_score'|'revenue'|'margin'|'savings'|'automation';
const rankingOptions:[NumericKey,string][]=[['overall_score','Nota geral'],['revenue','Receita'],['margin','Margem'],['savings','Redução de custos'],['automation','Automação']];
const criteria:[keyof ResultRow,string][]=[['revenue','Receita'],['margin','Margem'],['savings','Economia'],['ease','Facilidade'],['speed','Rapidez'],['scalability','Escalabilidade'],['automation','Automação'],['risk','Baixo risco'],['customer','Cliente'],['strategy','Estratégia']];

export function ResultsDashboard({code,published,title='Resultados'}:{code:string;published:boolean;title?:string}){
 const [rows,setRows]=useState<ResultRow[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [area,setArea]=useState('');const [classification,setClassification]=useState('');const [ranking,setRanking]=useState<NumericKey>('overall_score');
 const load=async()=>{if(!published||!configured)return;setLoading(true);setError('');const {data,error}=await supabase.rpc('brainstorm_get_published_results',{p_session_code:code});if(error)setError('Não foi possível carregar os resultados publicados.');else setRows((data||[]) as ResultRow[]);setLoading(false)};
 useEffect(()=>{void load()},[code,published]);
 const areas=useMemo(()=>[...new Set(rows.map(row=>row.area_name))],[rows]);const classes=useMemo(()=>[...new Set(rows.map(row=>row.classification))],[rows]);const filtered=rows.filter(row=>(!area||row.area_name===area)&&(!classification||row.classification===classification)).sort((a,b)=>Number(b[ranking]||0)-Number(a[ranking]||0));
 const totalVotes=rows.reduce((sum,row)=>sum+Number(row.vote_count),0);const totalContributions=rows.reduce((sum,row)=>sum+Number(row.contribution_count),0);const average=(key:keyof ResultRow)=>{const voted=rows.filter(row=>row.vote_count>0&&row[key]!=null);const weight=voted.reduce((sum,row)=>sum+Number(row.vote_count),0);return weight?voted.reduce((sum,row)=>sum+Number(row[key])*Number(row.vote_count),0)/weight:0};
 if(!published)return <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 text-center"><BarChart3 className="mx-auto text-slate-400" size={40}/><h2 className="mt-3 text-2xl font-black">{title}</h2><p className="mt-2 text-slate-600">Os resultados permanecerão ocultos até o facilitador finalizar a votação.</p></section>;
 return <section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-semibold text-brand-700">Fase 5</p><h2 className="text-3xl font-black">{title}</h2><p className="mt-1 text-slate-600">Ranking calculado com peso 1,30 para votos do próprio setor e 1,00 para os demais.</p></div><button className="btn-secondary" disabled={loading} onClick={load}><RefreshCw className="mr-2" size={17}/>{loading?'Atualizando…':'Atualizar'}</button></div>
  {error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-medium text-red-800">{error}</p>}
  <div className="mt-5 grid gap-3 sm:grid-cols-3"><Summary icon={<Trophy/>} label="Ideias classificadas" value={rows.length}/><Summary icon={<Vote/>} label="Avaliações recebidas" value={totalVotes}/><Summary icon={<Sparkles/>} label="Contribuições agrupadas" value={totalContributions}/></div>
  <div className="card mt-5"><div className="flex items-center gap-2"><BarChart3 className="text-brand-700"/><h3 className="font-bold">Médias gerais dos critérios</h3></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{criteria.map(([key,label])=><Score key={String(key)} label={label} value={average(key)}/>)}</div></div>
  <div className="card mt-5"><h3 className="font-bold">Explorar rankings</h3><div className="mt-4 grid gap-3 sm:grid-cols-3"><label><span className="label">Ordenar por</span><select className="field" value={ranking} onChange={e=>setRanking(e.target.value as NumericKey)}>{rankingOptions.map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label><span className="label">Setor</span><select className="field" value={area} onChange={e=>setArea(e.target.value)}><option value="">Todos os setores</option>{areas.map(name=><option key={name}>{name}</option>)}</select></label><label><span className="label">Classificação</span><select className="field" value={classification} onChange={e=>setClassification(e.target.value)}><option value="">Todas</option>{classes.map(name=><option key={name}>{name}</option>)}</select></label></div></div>
  <div className="mt-5 space-y-4">{filtered.map((row,index)=><article className="card" key={row.id}><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex min-w-0 gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-slate-900 text-lg font-black text-white">{index+1}</span><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-xl font-black">{row.title}</h3><span className={`rounded-full px-2 py-1 text-xs font-bold ${classColor(row.classification)}`}>{row.classification}</span></div><p className="mt-1 text-sm font-semibold text-brand-700">{row.area_name}</p>{row.description&&<p className="mt-2 text-slate-600">{row.description}</p>}</div></div><div className="text-right"><p className="text-3xl font-black text-brand-700">{Number(row[ranking]||0).toFixed(2)}</p><p className="text-xs text-slate-500">{rankingOptions.find(([key])=>key===ranking)?.[1]}</p></div></div>
   <div className="mt-5 grid gap-3 sm:grid-cols-4"><Mini label="Nota geral" value={`${Number(row.overall_score||0).toFixed(2)} / 5`}/><Mini label="Impacto" value={`${Number(row.impact||0).toFixed(2)} / 5`}/><Mini label="Viabilidade" value={`${Number(row.viability||0).toFixed(2)} / 5`}/><Mini label="Participação" value={`${row.vote_count} votos · ${row.contribution_count} contribuições`}/></div>
   <details className="mt-4 rounded-xl bg-slate-50 p-4"><summary className="cursor-pointer font-bold">Ver médias dos 10 critérios</summary><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{criteria.map(([key,label])=><Score key={String(key)} label={label} value={Number(row[key]||0)}/>)}</div></details>
  </article>)}{!loading&&filtered.length===0&&<div className="card text-center text-slate-500">Nenhum resultado encontrado para estes filtros.</div>}</div>
 </section>
}

function Summary({icon,label,value}:{icon:ReactNode;label:string;value:number}){return <div className="card flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-brand-50 text-brand-700">{icon}</span><div><p className="text-sm text-slate-500">{label}</p><p className="text-2xl font-black">{value}</p></div></div>}
function Score({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between gap-2 text-sm"><span>{label}</span><strong>{value.toFixed(2)}</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-brand-600" style={{width:`${Math.min(100,value/5*100)}%`}}/></div></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-slate-200 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-bold">{value}</p></div>}
function classColor(value:string){if(value==='Quick Win')return'bg-green-100 text-green-800';if(value==='Aposta Estratégica')return'bg-purple-100 text-purple-800';if(value==='Melhoria Incremental')return'bg-blue-100 text-blue-800';return'bg-slate-100 text-slate-700'}
